name: Run PHP static code checks

on:
  push:
    branches: [ "master" ]

jobs:
  code-check:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'

    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Check coding style
      run: composer cs

    - name: Execute phpstan checks
      run: composer phpstan

    - name: Execute tests
      run: composer test
