name: Run PHP static code checks

on:
  push:
    branches: [ "master" ]

jobs:
  code-check:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8.2', '8.3', '8.4']

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Check coding style
      run: vendor/bin/ecs check --clear-cache

    - name: Execute phpstan checks
      run: composer phpstan

    - name: Execute tests
      run: composer test
